version: "3.8"

services:
  go-ddd-db:
    image: postgres:14
    container_name: go-ddd-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_ddd
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - go-ddd-backend

  go-ddd-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-ddd-api
    ports:
      - "3003:3003"
    depends_on:
      - go-ddd-db
    volumes:
      - ./.env:/app/.env
    environment:
      - DB_HOST=go-ddd-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go_ddd
      - DB_PORT=5432
      - JWT_SECRET=mysecret
    networks:
      - go-ddd-backend

volumes:
  pg-data:

networks:
  go-ddd-backend:
